### ISSUE TITLE
Logging level not working as documented

### ISSUE THREAD

**Issue by LaurentChardon** [z80andrew/SerialDisk#21] opened 2020-09-20 17:59 UTC
The `--help` option shows that the default for `--logging-level` is `Verbose`
Yet running the program without the `--logging-level` argument defaults to `Info`. This needs to be consistent and either the default or the usage message needs to be changed. 
Personally I'd prefer it if `Verbose` really was the default, but I can live with it either way :) 
If `Verbose` had been the default I would have spent less time chasing after a ghost serial port error that is most likely due to something else.

**Comment by z80andrew** [comment] 2020-09-20 19:02
Thanks for the detailed bug report, Laurent.

This was caused by an inconsistency between the OS-specific resource config file (verbose) which is used for the defaults, and the serialdisk.config (info) on the file system which is loaded later and intended for user overrides. The logging level in the config files were made consistent (info) in v2.4. 

Having said that, you've highlighted a situation where someone may change the settings in serialdisk.config, which will then _not_ be reported as the defaults and potentially cause confusion. I'll work on a fix to make this clearer / more intuitive.

As for info vs verbose as the default, I think that comes down to personal preference. I chose info as it shows what I believe most people will be interested in, i.e. data transfers and progress. Verbose was intended for debugging and troubleshooting, so as not to overwhelm a new user with lots of potentially unimportant information.
For those who prefer verbose logging, it's simply a matter of changing the setting in serialdisk.config once.

**Comment by LaurentChardon** [comment] 2020-09-20 22:00
Thanks for looking into it! I agree that it's completely a matter of preference. 
If I may suggest, I think that an extra level, `None` for example, would be nice, that would hide all the sector information. Just my $0.02.

**Comment by z80andrew** [comment] 2020-09-24 21:24
`serialdisk.config` file is now used (if available) when displaying defaults via `--help`.
Sector information moved to Verbose to keep Info as minimal as possible.

I will review the logging levels when moving to .NET 5 later this year, as this is lower priority than some of the other current issues. The levels don't reflect common logging nomenclature but I don't want to change it until the next major version.

**Comment by z80andrew** [comment] 2020-10-15 00:44
Verbose has been renamed to All, and a new intermediate logging level Debug has been created.

So from least to most logging, we now have: Info - Debug - All.

**Closed** 2020-11-29 19:35 UTC
Labels: .NET, bug, ready for release
